Thực Hành 1

In [24]:
import numpy as np
#Yêu cẩu 1 :
array_rd = np.random.randint(low=0,high=100,size=(12,12),dtype=int)
print(array_rd)
print("Kiểu dữ liệu của phần tử : ",array_rd.dtype)
print("Kích thước của mảng ma trận : ",array_rd.shape)
print("Số phần tử củ mảng ma trận :",array_rd.size)
print("Số chiều của mảng ma trận :",array_rd.ndim)
#Yêu cầu 2 :
vector_c= np.diag(array_rd)
vector_p = np.diag(np.fliplr(array_rd))
print("Đường chéo chính là :",vector_c)
print("Đường chéo phụ là :",vector_p)
#Yêu cầu 3 :
so=int(input("Nhập vào số nguyên 0-100 :"))
array_bang = np.sum(array_rd == so)
array_nho =np.sum(array_rd < so)
array_lon = np.sum(array_rd > so)
print("Số phần tử có giá trị bằng ",so,"trong ma trận trên là :",array_bang)
print("Số phần tử có giá trị nhỏ hơn ",so,"trong ma trận trên là :",array_nho)
print("Số phần tử có giá trị lớn hơn ",so,"trong ma trận trên là :",array_lon)
                 

[[81 28 60 27 75 19 13 95  3 25 75 95]
 [88 97 22 76 27 44 85 87 25  8 21 56]
 [24 34 85 39 93  6 96  9 45 17 46 52]
 [13 54 82 37 95 97 32 41 61 33 83 67]
 [31 15 95 58 65 42 48 20 53 60 89 83]
 [47 25 82 63 28 98  4 19 95  5  1 78]
 [29 50 35 88 32 66 20 20 70 15 66 90]
 [75 47 70 47 60 33 52 98 95 38 96 93]
 [51 57 23 44 53 19 19 15 57 36 50  7]
 [19 33 29 88 68  1 50 12 63 68 17 24]
 [24 92 83  6 33 50 31 21 50  2 62 36]
 [73 35 44 65 21 27 28 96  4 10 63 83]]
Kiểu dữ liệu của phần tử :  int32
Kích thước của mảng ma trận :  (12, 12)
Số phần tử củ mảng ma trận : 144
Số chiều của mảng ma trận : 2
Đường chéo chính là : [81 97 85 37 65 98 20 98 57 68 62 83]
Đường chéo phụ là : [95 21 17 61 20  4 66 60 44 29 92 73]


Nhập vào số nguyên 0-100 : 36


Số phần tử có giá trị bằng  36 trong ma trận trên là : 2
Số phần tử có giá trị nhỏ hơn  36 trong ma trận trên là : 59
Số phần tử có giá trị lớn hơn  36 trong ma trận trên là : 83


Thực Hành 2

In [3]:
import numpy as np
diem_2a = np.array([
    [2, 4, 3, 7, 5, 6, 5, 6, 8, 9, 3, 6, 1, 9, 8, 7, 3, 3, 9, 5],
    [3, 5, 3,10, 9, 1, 9, 8, 3, 1, 6, 0, 7,10, 8, 5, 2, 7, 7, 1],
    [1,10, 4, 9, 6, 9, 0, 2, 3, 1, 8, 6, 8, 4, 2, 9, 2, 9, 5, 0],
    [6, 3, 0, 8, 3, 7, 7, 2, 6, 8, 7, 3, 4, 1, 5, 9, 1, 0, 2,10],
    [4, 3, 6, 7, 4, 5, 2, 6, 9, 4, 3, 9, 9, 4, 5, 7, 2,10, 9, 4],
    [2, 3, 8,10, 4, 5, 9, 5, 4, 7,10, 1, 8, 4, 3, 9, 6, 3, 6, 7],
    [9, 9, 1,10, 9, 9, 5, 9, 6, 3, 9, 5, 1,10, 7,10, 2, 8, 8, 1],
    [8, 8, 7, 8, 6, 7, 7, 8, 6, 7, 8, 6, 7, 6, 8, 8, 7, 6, 8, 8],
    [6, 7, 8, 9,10, 9, 2, 2, 6, 1,10, 9, 6, 3, 9, 5, 9, 8, 1, 1],
    [7, 8, 7, 8, 6,10,10, 6, 8,10, 8, 9, 8, 8, 5,10, 8, 7, 8, 7]
])
print("Kiểu dữ liệu của mảng diem_2a là :",diem_2a.dtype)
print("Kích thước của mảng diem_2a là :",diem_2a.shape)
print("Số phần tử của mảng diem_2a là :",diem_2a.size)
print("Số chiều của mảng diem_2a là :",diem_2a.ndim)
#Yêu Cầu 1 :
diemtb_hs =diem_2a.mean(axis=0)
print(diemtb_hs)
print("Học sinh có điểm trung bình cao nhất là :",diemtb_hs.max())
print("Của học sinh thứ :",diemtb_hs.argmax())
print("Bảng điểm của học sinh đó là :",diem_2a[:,3])
print("Học sinh có điểm trung bình thấp nhất là :",diemtb_hs.min())
print("Của học sinh thứ :",diemtb_hs.argmin())
print("Bảng điểm của học sinh đó là :",diem_2a[:,16])
#Yêu Cầu 2 :
diemtb_mh = diem_2a.mean(axis=1)
print(diemtb_mh)
print("Môn học có điểm trung bình cao nhất là :",diemtb_mh.max())
print("Môn học thứ :",diemtb_mh.argmax())
print("Bảng điểm của môn học đó là :",diem_2a[9,:])
print("Môn học có điểm trung bình thấp nhất là :",diemtb_mh.min())
print("Môn học thứ :",diemtb_mh.argmin())
print("Bảng điểm của môn học đó là :",diem_2a[3,:])
#Yêu cầu 3 :
dolech_hs = diem_2a.std(axis=0)
print("Học sinh có điểm đồng đều nhất là :",dolech_hs.argmin())
print("Bảng điểm của học sinh đồng đều là :",diem_2a[:,3])
print("Học sinh có điểm lệch chuẩn nhất là :",dolech_hs.argmax())
print("Bảng điểm của học sinh lệch chuẩn  là :",diem_2a[:,19])
dolech_mh = diem_2a.std(axis=1)
print("Môn học có điểm đồng đều nhất là :",dolech_mh.argmin())
print("Bảng điểm của môn học đồng đều là :",diem_2a[7,:])
print("Môn học có điểm lệch chuẩn nhất là :",dolech_mh.argmax())
print("Bảng điểm của môn học lệch chuẩn là :",diem_2a[2,:])


Kiểu dữ liệu của mảng diem_2a là : int64
Kích thước của mảng diem_2a là : (10, 20)
Số phần tử của mảng diem_2a là : 200
Số chiều của mảng diem_2a là : 2
[4.8 6.  4.7 8.6 6.2 6.8 5.6 5.4 5.9 5.1 7.2 5.4 5.9 5.9 6.  7.9 4.2 6.1
 6.3 4.4]
Học sinh có điểm trung bình cao nhất là : 8.6
Của học sinh thứ : 3
Bảng điểm của học sinh đó là : [ 7 10  9  8  7 10 10  8  9  8]
Học sinh có điểm trung bình thấp nhất là : 4.2
Của học sinh thứ : 16
Bảng điểm của học sinh đó là : [3 2 2 1 2 6 2 7 9 8]
[5.45 5.25 4.9  4.6  5.6  5.7  6.55 7.2  6.05 7.9 ]
Môn học có điểm trung bình cao nhất là : 7.9
Môn học thứ : 9
Bảng điểm của môn học đó là : [ 7  8  7  8  6 10 10  6  8 10  8  9  8  8  5 10  8  7  8  7]
Môn học có điểm trung bình thấp nhất là : 4.6
Môn học thứ : 3
Bảng điểm của môn học đó là : [ 6  3  0  8  3  7  7  2  6  8  7  3  4  1  5  9  1  0  2 10]
Học sinh có điểm đồng đều nhất là : 3
Bảng điểm của học sinh đồng đều là : [ 7 10  9  8  7 10 10  8  9  8]
Học sinh có điểm lệch chuẩn nhất là : 19
Bảng 

Thực hành 4

In [36]:
import numpy as np
path = "C:/Users/Admin/Downloads/Temp.txt"
data_numpy=np.loadtxt(path)
#Yêu cầu 1 :
print(data_numpy)
print("Kích thước của biến là :",data_numpy.shape)
print("Số chiều của biến là :",data_numpy.ndim)
print("Kiểu dữ liệu của các phần tử là :",data_numpy.dtype)
print("Số phần tử là :",data_numpy.size)
#Yêu Cầu 2 :
print("Thống kê cả sáu thành phố")
print("Nhiệt độ cao nhất là :",data_numpy.max())
print("Nhiệt độ thấp nhất là :",data_numpy.min())
print("Nhiệt độ trung bình là :",data_numpy.mean())
#Yêu Cầu 3 :
print("1) Hà Nội")
print("Nhiệt độ cao nhất là :",data_numpy[:,0].max())
print("Nhiệt độ thấp nhất là :",data_numpy[:,0].min())
print("Nhiệt độ trung bình là :",data_numpy[:,0].mean())
print("1) Vinh")
print("Nhiệt độ cao nhất là :",data_numpy[:,1].max())
print("Nhiệt độ thấp nhất là :",data_numpy[:,1].min())
print("Nhiệt độ trung bình là :",data_numpy[:,1].mean())
print("1) Đà Nẵng")
print("Nhiệt độ cao nhất là :",data_numpy[:,2].max())
print("Nhiệt độ thấp nhất là :",data_numpy[:,2].min())
print("Nhiệt độ trung bình là :",data_numpy[:,2].mean())
print("1) Nha Trang")
print("Nhiệt độ cao nhất là :",data_numpy[:,3].max())
print("Nhiệt độ thấp nhất là :",data_numpy[:,3].min())
print("Nhiệt độ trung bình là :",data_numpy[:,3].mean())
print("1) TP Hồ Chí Minh")
print("Nhiệt độ cao nhất là :",data_numpy[:,4].max())
print("Nhiệt độ thấp nhất là :",data_numpy[:,4].min())
print("Nhiệt độ trung bình là :",data_numpy[:,4].mean())
print("1) Cà Mau")
print("Nhiệt độ cao nhất là :",data_numpy[:,5].max())
print("Nhiệt độ thấp nhất là :",data_numpy[:,5].min())
print("Nhiệt độ trung bình là :",data_numpy[:,5].mean())
#Yêu Cầu 4 :
data_ThongKe1 = np.array([data_numpy[:,0].max() , data_numpy[:,1].max() , data_numpy[:,2].max() , data_numpy[:,3].max() ,data_numpy[:,4].max() ,data_numpy[:,5].max()])
data_ThongKe2 = np.array([np.round(data_numpy[:,0].mean(),2),np.round(data_numpy[:,1].mean(),2),np.round(data_numpy[:,2].mean(),2),np.round(data_numpy[:,3].mean(),2),np.round(data_numpy[:,4].mean(),2),np.round(data_numpy[:,5].mean(),2)])
data_ThongKe3 = np.array([data_numpy[:,0].min(),data_numpy[:,1].min(),data_numpy[:,2].min(),data_numpy[:,3].min(),data_numpy[:,4].min(),data_numpy[:,5].min()])                                            
data_ThongKe = np.concatenate((data_ThongKe1,data_ThongKe2,data_ThongKe3))
print(data_ThongKe)

[[25.65 24.79 24.01 25.06 25.48 24.97]
 [25.31 24.21 24.02 24.93 25.16 24.83]
 [25.05 23.73 23.89 24.79 24.8  24.55]
 ...
 [24.81 24.47 23.4  25.86 25.05 25.29]
 [23.97 24.22 22.95 25.74 24.92 24.87]
 [22.84 23.99 22.59 25.5  24.77 24.57]]
Kích thước của biến là : (192, 6)
Số chiều của biến là : 2
Kiểu dữ liệu của các phần tử là : float64
Số phần tử là : 1152
Thống kê cả sáu thành phố
Nhiệt độ cao nhất là : 33.45
Nhiệt độ thấp nhất là : 20.93
Nhiệt độ trung bình là : 26.50222222222222
1) Hà Nội
Nhiệt độ cao nhất là : 33.45
Nhiệt độ thấp nhất là : 21.68
Nhiệt độ trung bình là : 27.71229166666667
1) Vinh
Nhiệt độ cao nhất là : 32.57
Nhiệt độ thấp nhất là : 22.6
Nhiệt độ trung bình là : 26.719895833333336
1) Đà Nẵng
Nhiệt độ cao nhất là : 29.88
Nhiệt độ thấp nhất là : 20.93
Nhiệt độ trung bình là : 25.522499999999997
1) Nha Trang
Nhiệt độ cao nhất là : 28.68
Nhiệt độ thấp nhất là : 24.5
Nhiệt độ trung bình là : 26.166875000000005
1) TP Hồ Chí Minh
Nhiệt độ cao nhất là : 31.06
Nhiệt độ thấ

Thực Hành 5

In [47]:
import numpy as np
path = "C:/Users/Admin/Downloads/Diamonds.txt"
data_diamond = np.loadtxt(path)
#Yêu Cầu 1 :
print(data_diamond)
print("Kích thước của biến là :",data_diamond.shape)
print("Số chiều của biến là :",data_diamond.ndim)
print("Kiểu dữ liệu của các phần tử là :",data_diamond.dtype)
print("Số phần tử là :",data_diamond.size)
#Yêu Cầu 2 :
result = np.hsplit(data_diamond,2)
print(result)
#Yêu Cầu 3 :
#Yêu Cầu 4 :
print("Trọng lượng trung bình 50 viên kim cương là :",data_diamond[:,0].mean())
print("Giá trung bình 50 viên kim cương là :",data_diamond[:,1].mean())


[[2.3000e-01 4.8400e+02]
 [3.1000e-01 9.4200e+02]
 [2.0000e-01 3.4500e+02]
 [1.0200e+00 4.4590e+03]
 [1.6300e+00 1.4022e+04]
 [1.1400e+00 4.2120e+03]
 [2.0100e+00 1.1925e+04]
 [1.2800e+00 9.5480e+03]
 [1.7000e+00 1.1605e+04]
 [1.0100e+00 4.6420e+03]
 [6.4000e-01 3.5410e+03]
 [9.7000e-01 4.5040e+03]
 [1.7800e+00 1.3691e+04]
 [3.4000e+00 1.5964e+04]
 [3.0100e+00 1.0453e+04]
 [1.5100e+00 1.1560e+04]
 [1.3700e+00 7.9790e+03]
 [1.5000e+00 9.5330e+03]
 [5.4000e-01 1.7230e+03]
 [7.2000e-01 3.3440e+03]
 [1.1300e+00 6.1330e+03]
 [2.2400e+00 1.3827e+04]
 [3.0100e+00 1.6538e+04]
 [4.5000e+00 1.8531e+04]
 [9.2000e-01 3.6250e+03]
 [1.0500e+00 7.8790e+03]
 [5.5000e-01 1.3190e+03]
 [7.4000e-01 2.7610e+03]
 [9.1000e-01 3.6200e+03]
 [1.2300e+00 6.1650e+03]
 [1.5200e+00 1.0640e+04]
 [9.1000e-01 4.1380e+03]
 [4.3000e-01 1.0940e+03]
 [1.2400e+00 1.1130e+04]
 [1.7700e+00 1.4561e+04]
 [1.7900e+00 1.0108e+04]
 [2.0500e+00 1.2654e+04]
 [2.0300e+00 1.6280e+04]
 [2.0100e+00 1.3498e+04]
 [1.0000e+00 4.5860e+03]


Thực Hành

In [43]:
import numpy as np
a = np.arange(1,31)
print(a)
a_le = a[a % 2 == 1]
a_chan = a[a % 2 == 0]
a_het = a[a % 3 == 0]
print("Các phần tử số lẻ là :",a_le)
print("Các phần tử số chẵn là :",a_chan)
print("Các phần tử số chia hết cho 3 là :",a_het)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Các phần tử số lẻ là : [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
Các phần tử số chẵn là : [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
Các phần tử số chia hết cho 3 là : [ 3  6  9 12 15 18 21 24 27 30]
